### PR TITLE
Add sync-with-meilisearch template in Kotlin

### LINKED ISSUE #192: 🚀 Feature: Add Sync with Meilisearch for Kotlin
Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code. 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement the Sync with Meilisearch function in Kotlin. You can look at the existing [Appwrite Functions Templates](https://github.com/appwrite/templates) in another coding language.

Your function should behave and be implemented similarly to existing Sync with Meilisearch Node.js template.

### Tasks summary:

- [ ] Fork & clone Appwrite's [templates](https://github.com/appwrite/templates) repository
- [ ] Create a branch `feat-implement-sync-with-meilisearch-kotlin`
- [ ] Write code for the function in folder `kotlin/sync-with-meilisearch/`. 
- [ ] Test the function using Appwrite, **provide a video**.
- [ ] Write a `README.md` explaining what the function does, how to use it, and customize it. Here is [an example](https://github.com/appwrite/templates/tree/main/node/sync-with-meilisearch).
- [ ] Submit a pull request to our [templates](https://github.com/appwrite/templates) repository

If you need any help, contact us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by ShamanthOP**
## What does this PR do?

Add sync-with-meilisearch template in Kotlin.

## Test Plan

https://github.com/appwrite/templates/assets/69506046/2b81ecde-06d7-4e44-ad1f-339d421c502a

image

## Related PRs and Issues

Closes #192 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by ShamanthOP** [comment]
> Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

Thanks @stnguyen90! What about the static file thing, I tried the suggestions from the PR review party but still no luck😔

**Comment by gewenyu99** [comment]
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

**Comment by ShamanthOP** [comment]
It's `shamanth8360`

**Comment by gewenyu99** [comment]
Be in touch soon!

**Pull request merged**
